on: [push]
    branches:
    - '**'
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://codeberg.org/Silejonu/dotfiles'
            GIT_USERNAME: silejonu
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
